[package]
name = "pjproject-sys"
version = "0.1.0"
edition = "2021"
links = "pjproject"
build = "build.rs"

[lib]
doctest = false

[dependencies]


[build-dependencies]
bindgen = "0.59.2"
make-cmd = "0.1.0"